### ISSUE TITLE
Feature Request:Add Memo space

### ISSUE THREAD

**Issue by Maximilian2022** [Naoya79/Among-Us-Discord-Overlay#1]
作者様
いつもお世話になっております。

メンバーリストの下あたりに、メモをうてるスペースを追加できませんでしょうか。
ご一考何卒宜しくお願い致します。

**Comment by Naoya79** [comment]
@Maximilian2022 様
本アプリのご利用、並びに貴重なご意見ありがとうございます。

サイドバーにメモスペースを追加いたしました。
アプリのバージョンが2.1.0になっていればご利用いただけます。

今後とも『Among Us Discord Overlay』をよろしくお願いいたします。
